# Generated by Django 5.2.3 on 2025-07-07 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0003_video_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='is_premium',
            field=models.BooleanField(default=False),
        ),
    ]
